name: ac-labeler
author: '@schoi-godaddy'
description: 'Labels based on AC met on a PR.'
inputs:
  label:
    description: 'label to add on the PR if requirements are met.'
    required: true
  minCompletedTaskCount:
    description: '(Optional) Minimum "integer" number of Completed Task PR needs to contain.'
    required: false
  minCompletedTaskPercentage:
    description: '(Optional) Minimum % "integer" of Completed Task PR needs to contain. If `minCompletedTaskCount` is set, this field is ignored.'
    required: false
outputs:
  labelAdded: # id of output
    description: 'If label was added or not.'
runs:
  using: 'node16'
  main: 'dist/index.js'
