name: "Label the PR"

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  main:
    name: Label the PR
    runs-on: ubuntu-latest
    steps:
      - uses: schoi-godaddy/ac-labeler@feature/main-code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          label: "bug"
          minCompletedTaskPercentage: 45
